
<field:language itemname="语言" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="国语,粤语,英语,日韩,其他"  maxlength="250" page="">
</field:language>


<field:zhuyan itemname="主演" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zhuyan>

<field:daoyan itemname="导演" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:daoyan>

<field:diqu itemname="地区" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="大陆,香港,台湾,欧美,日韩"  maxlength="250" page="">
</field:diqu>

<field:pfrs itemname="评分人数" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pfrs>

<field:pf itemname="评分分值" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pf>

<field:desc itemname="简介" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:desc>

<field:nianda itemname="年代" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:nianda>
